# Generated by Django 5.2.8 on 2025-12-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usermodel',
        ),
    ]
